### ISSUE TITLE
Not Showing All Related Taxonomies?

### ISSUE THREAD

**Issue by watermelonkid** [franz-josef-kaiser/filterama#4]
Sorry for using this as a support thread, but I can't contact you otherwise. 

Installed, I should see all associated taxonomies with a CPT, correct? For some reason I'm only seeing one of two associated taxonomies with my build. Is there anything special that needs to be done to get a taxonomy to have a filter?

**Comment by franz-josef-kaiser** [comment]
I assume that those do not have admin columns. We can reopen this in case there's a different problem.
