### ISSUE TITLE
Wordpress 4 Issues?

### ISSUE THREAD

**Issue by zachatkinson** [franz-josef-kaiser/filterama#8]
Hi there, cant seem to get this working on WP4 - can anyone confirm it's working right now?

**Comment by toomuchdesign** [comment]
Hi everybody,
I suggest to check that the Custom Post Type Taxonomy declaration includes `show_admin_column => true` among its `$args` array. The setting is available since WP 3.5 and its `false` by default.

**Comment by franz-josef-kaiser** [comment]
@toomuchdesign Thanks for the support here. I would like to give you commit access to this repo as thank you for helping out. Would you like to have that?

Closing this one until there's more info.

**Comment by toomuchdesign** [comment]
@franz-josef-kaiser Hi Franz,
thanks for the opportunity! I've recently stopped using Wordpress on a daily basis, so I won't be super-updated about the last wordpress tricks. Anyway, I really owe a lot to your WP plugins, so I'll be happy to help when I'll be able to!

**Comment by franz-josef-kaiser** [comment]
@toomuchdesign You are an official collaborator now :)

Ps.: What exactly are you working on right now?

**Comment by toomuchdesign** [comment]
Great! I sent you an email.
